name: pull request
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  pull_request:
    branches:
      - main
      
env:
  ## Sets environment variable
  database98365: testinngggg
  bucketName: testwebappashish12.dev.domain.tld
  bucket_name: bucket.dev.ashishpandey.me
  ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: AKIAZFAFK6BV563J5HWI
  AWS_SECRET_ACCESS_KEY: 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
  S3_CODEDEPLOY_BUCKET: ashish-csye6225
  snstopic: testSns
  snstopicArn: testSnsArn

jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Run Tests
      - name: Run Tests
        run: |
          mvn clean install