AWSTemplateFormatVersion: 2010-09-09
Description: Add neccesary roles and permissions to build packer image
Parameters:
  AwsAccountID:
    Default: "AccountId"
    Type: String
  ApplicationName:
    Default: "csye6225-webapp"
    Type: String
  AwsRegion:
    Default: "us-east-1"
    Type: String
  CDBucketName:
    Default: "demo-ashish-csye6225"
    Type: String
  SNSTopic:
    Default: "arn:aws:sns:us-east-1:AccountId:create_token"
    Type: String

Resources:
  GHPackerUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: gh-ec2-ami
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - ec2:AttachVolume
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CopyImage
              - ec2:CreateImage
              - ec2:CreateKeypair
              - ec2:CreateSecurityGroup
              - ec2:CreateSnapshot
              - ec2:CreateTags
              - ec2:CreateVolume
              - ec2:DeleteKeyPair
              - ec2:DeleteSecurityGroup
              - ec2:DeleteSnapshot
              - ec2:DeleteVolume
              - ec2:DeregisterImage
              - ec2:DescribeImageAttribute
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ec2:DescribeRegions
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSnapshots
              - ec2:DescribeSubnets
              - ec2:DescribeTags
              - ec2:DescribeVolumes
              - ec2:DetachVolume
              - ec2:GetPasswordData
              - ec2:ModifyImageAttribute
              - ec2:ModifyInstanceAttribute
              - ec2:ModifySnapshotAttribute
              - ec2:RegisterImage
              - ec2:RunInstances
              - ec2:StopInstances
              - ec2:TerminateInstances
            Resource:
              - "*"
      Users:
        -
          ghactions-app
  GHUploadToS3UserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${CDBucketName}
              - !Sub arn:aws:s3:::${CDBucketName}/*
      Users:
        - ghactions-app
      ManagedPolicyName: GH-Upload-To-S3
  GHCodeDeployUserPolciy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GH-Code-Deploy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codedeploy:RegisterApplicationRevision
              - codedeploy:GetApplicationRevision
            Resource:
              - !Sub arn:aws:codedeploy:${AwsRegion}:${AwsAccountID}:application:${ApplicationName}
          - Effect: Allow
            Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetDeployment
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - codedeploy:GetDeploymentConfig
            Resource:
              - !Sub arn:aws:codedeploy:${AwsRegion}:${AwsAccountID}:deploymentconfig:CodeDeployDefault.OneAtATime
              - !Sub arn:aws:codedeploy:${AwsRegion}:${AwsAccountID}:deploymentconfig:CodeDeployDefault.HalfAtATime
              - !Sub arn:aws:codedeploy:${AwsRegion}:${AwsAccountID}:deploymentconfig:CodeDeployDefault.AllAtOnce
      Users:
      - ghactions-app
