version: 0.0
os: linux

files:
  - source: ./target/assignment-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user
  - source: ./cloudwatch-config.json
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
  - location: ./codedeploy/beforeInstall.sh
    timeout: 180
    runas: ec2-user

  AfterInstall:
  - location: ./codedeploy/afterInstall.sh
    timeout: 180
    runas: ec2-user

  ApplicationStart:
  - location: ./codedeploy/applicationStart.sh
    timeout: 180
    runas: ec2-user


    
    
